-- 코드를 입력하세요
SELECT PRODUCT_CODE , SUM(PRICE * SALES_AMOUNT)  AS SALES
FROM (
    SELECT  A.PRODUCT_CODE, A.PRICE, B.SALES_AMOUNT
    FROM PRODUCT A , OFFLINE_SALE B
    WHERE 1=1 
     AND A.PRODUCT_ID = B.PRODUCT_ID
    )
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC