-- -- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT A.ANIMAL_ID, A.NAME
    , A.DATETIME AS OUT_D, B.DATETIME AS IN_D
    , (A.DATETIME - B.DATETIME +1 ) AS DAY
    FROM ANIMAL_OUTS A 
    LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE A.ANIMAL_ID IS NOT NULL
      AND B.DATETIME IS NOT NULL
      AND A.DATETIME > B.DATETIME 
    ORDER BY DAY DESC
    )
WHERE ROWNUM <= 2 


-- SELECT A.ANIMAL_ID, A.NAME
-- , A.DATETIME AS OUT_D, B.DATETIME AS IN_D
-- , (A.DATETIME - B.DATETIME +1 ) AS DAY
-- FROM ANIMAL_OUTS A 
-- LEFT JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
-- WHERE A.ANIMAL_ID IS NOT NULL
--   AND B.DATETIME IS NOT NULL
--   AND A.DATETIME > B.DATETIME 
-- ORDER BY DAY DESC