-- 코드를 입력하세요
-- SELECT CAR_ID  , AVAILABILITY
-- FROM ( 
--         SELECT CAR_ID 
--              , START_DATE
--              , END_DATE 
--              , CASE WHEN TO_CHAR(END_DATE,'YYYY-MM-DD') = '2022-10-16'  THEN '대여중'
--                     WHEN '2022-10-16' BETWEEN TO_CHAR(START_DATE,'YYYY-MM-DD') AND TO_CHAR(END_DATE,'YYYY-MM-DD') THEN '대여중'
--                     ELSE '대여 가능' END AVAILABILITY
--              , ROW_NUMBER() OVER (PARTITION BY car_id ORDER BY end_date DESC) AS RNK
--     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
--     ORDER BY CAR_ID DESC
--     )
-- WHERE RNK = 1 
-- ORDER BY CAR_ID DESC

-- 코드를 입력하세요
SELECT CAR_ID
     , MAX(CASE WHEN '20221016' BETWEEN TO_CHAR(START_DATE, 'YYYYMMDD') AND TO_CHAR(END_DATE, 'YYYYMMDD') THEN '대여중'
                ELSE '대여 가능' END) AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 GROUP BY CAR_ID
 ORDER BY CAR_ID DESC