-- 코드를 입력하세요
SELECT B.INGREDIENT_TYPE , SUM(TOTAL_ORDER) AS TOTAL_ORDER
-- A.* , B.*
FROM FIRST_HALF A , ICECREAM_INFO B
WHERE 1=1
  AND A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC